CC = g++
FLAGS = -std=c++11 -pedantic -Wall -Werror -Wextra

all:
	${CC} ${FLAGS} main.cpp -o oop_exercise_01

run: # запуск тестов
	./oop_exercise_01 < test0.txt
	./oop_exercise_01 < test1.txt
	./oop_exercise_01 < test2.txt
	./oop_exercise_01 < test3.txt
	./oop_exercise_01 < test4.txt